#coin,stocks list report
stockd = ['TSLA','AAPL','GOOG','BDMS.BK','AMA.BK','VL.BK','RSP.BK','CPALL.BK','LH.BK']

stock_list = {
    'TSLA':{
    'name':'TSLA',
    'currency':'USD',
    'precision':'2',
    'open':'1'
    },
    'AAPL':{
    'name':'AAPL',
    'currency':'USD',
    'precision':'2',
    'open':'1'
    },
    'GOOG':{
    'name':'GOOG',
    'currency':'USD',
    'precision':'2',
    'open':'1'
    },
    'BDMS':{
    'name':'BDMS.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    },
    'AMA':{
    'name':'AMA.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    },
    'VL':{
    'name':'VL.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    },
    'RSP':{
    'name':'RSP.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    },
    'CPALL':{
    'name':'CPALL.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    },
    'LH':{
    'name':'LH.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    }
}

coin_list = {
    "BTC":{
    "name":"BTC",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
    "ETH":{
    "name":"ETH",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
    "OP":{
    "name":"OP",
    "currency":"USD",
    "precision":"3",
    "open":"1"
    },
    "ARB":{
    "name":"ARB11841",
    "currency":"USD",
    "precision":"3",
    "open":"1"
    },
    "ZCX":{
    "name":"ZCX",
    "currency":"USD",
    "precision":"3",
    "open":"0"
    },
    "SNX":{
    "name":"SNX",
    "currency":"USD",
    "precision":"3",
    "open":"1"
    },
    "VELA":{
    "name":"VELA",
    "currency":"USD",
    "precision":"3",
    "open":"0"
    },
    "RPL":{
    "name":"RPL",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
    "RDNT":{
    "name":"RDNT",
    "currency":"USD",
    "precision":"3",
    "open":"1"
    },
    "UNI":{
    "name":"UNI7083",
    "currency":"USD",
    "precision":"3",
    "open":"1"
    },
    "MATIC":{
    "name":"MATIC",
    "currency":"USD",
    "precision":"3",
    "open":"0"
    }
}