#coin,stocks list report
stockd = ['TSLA','AAPL','GOOG','BDMS.BK','AMA.BK','VL.BK','RSP.BK','CPALL.BK','LH.BK']
coin_list = {
    "BTC":{
    "name":"BTC",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
    "ETH":{
    "name":"ETH",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
    "OP":{
    "name":"OP",
    "currency":"USD",
    "precision":"4",
    "open":"1"
    },
    "ARB":{
    "name":"ARB11841",
    "currency":"USD",
    "precision":"4",
    "open":"1"
    },
    "ZCX":{
    "name":"ZCX",
    "currency":"USD",
    "precision":"4",
    "open":"1"
    },
    "SNX":{
    "name":"SNX",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
    "VELA":{
    "name":"VELA",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
    "RPL":{
    "name":"RPL",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
    "RDNT":{
    "name":"RDNT",
    "currency":"USD",
    "precision":"4",
    "open":"1"
    },
    "UNI":{
    "name":"UNI7083",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    }
}