#coin,stocks list report
stockd = ['TSLA','AAPL','GOOG','BDMS.BK','AMA.BK','VL.BK','RSP.BK','CPALL.BK','LH.BK']

stock_list = {
    'TSLA':{
    'name':'TSLA',
    'currency':'USD',
    'precision':'2',
    'open':'1'
    },
    'AAPL':{
    'name':'AAPL',
    'currency':'USD',
    'precision':'2',
    'open':'1'
    },
    'GOOG':{
    'name':'GOOG',
    'currency':'USD',
    'precision':'2',
    'open':'1'
    },
    'BDMS':{
    'name':'BDMS.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'0'
    },
    'AMA':{
    'name':'AMA.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    },
    'VL':{
    'name':'VL.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    },
    'RSP':{
    'name':'RSP.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    },
    'CPALL':{
    'name':'CPALL.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'0'
    },
    'LH':{
    'name':'LH.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'0'
    },
    'CPF':{
    'name':'CPF.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'0'
    },
    'BGRIM':{
    'name':'BGRIM.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    },
    'CBG':{
    'name':'CBG.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    },
    'PTG':{
    'name':'PTG.BK',
    'currency':'BAHT',
    'precision':'2',
    'open':'1'
    }
}

coin_list = {
    "BTC":{
    "name":"BTC",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
    "ETH":{
    "name":"ETH",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
    "OP":{
    "name":"OP",
    "currency":"USD",
    "precision":"3",
    "open":"1"
    },
    "ARB":{
    "name":"ARB11841",
    "currency":"USD",
    "precision":"3",
    "open":"1"
    },
    "SNX":{
    "name":"SNX",
    "currency":"USD",
    "precision":"3",
    "open":"1"
    },
    "RPL":{
    "name":"RPL",
    "currency":"USD",
    "precision":"2",
    "open":"0"
    },
    "RDNT":{
    "name":"RDNT",
    "currency":"USD",
    "precision":"3",
    "open":"1"
    },
    "UNI":{
    "name":"UNI7083",
    "currency":"USD",
    "precision":"3",
    "open":"1"
    },
    "CAKE":{
    "name":"CAKE",
    "currency":"USD",
    "precision":"3",
    "open":"0"
    },
    "BNB":{
    "name":"BNB",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
    "SD":{
    "name":"SD",
    "currency":"USD",
    "precision":"3",
    "open":"1"
    }
}

list_anyting = {
    "VOO":{
    "name":"VOO",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },"SPY":{
    "name":"SPY",
    "currency":"USD",
    "precision":"2",
    "open":"1"
    },
}